
export const URL = 'http://10.0.2.2:80/Darbiniai/locations_app/backend/public/api';
export const LOG_IN_ADMIN = 'LOG_IN_ADMIN';
export const LOG_IN_WORKER = 'LOG_IN_WORKER';
export const FETCH_ALL_WORKERS = 'FETCH_ALL_WORKERS';
export const FETCH_WORKER = 'FETCH_WORKER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_WORKER = 'REGISTER_WORKER'; 
export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';

//Workers
export const FETCH_WORKER_PROFILE = 'FETCH_WORKER_PROFILE';
export const FETCH_WORKER_PROFILE_ERROR = 'FETCH_WORKER_PROFILE_ERROR';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_lOCATION_ERROR = 'FETCH_lOCATION_ERROR';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR';
export const FETCH_LAST_LOCATIONS = 'FETCH_LAST_LOCATION';
export const FETCH_LAST_LOCATIONS_ERROR = 'FETCH_LAST_LOCATION_ERROR';
export const FETCH_LAST_LOCATION = 'FETCH_LAST_LOCATION';
export const FETCH_LAST_LOCATION_ERROR = 'FETCH_LAST_LOCATION_ERROR';